#!/bin/bash

# WildlifeSystems
#
# This script is part of the WildlifeSystems project. For further information
# please refer to https://docs.wildlife.systems, or for more information on
# the project itself, please refer to https://wildlife.systems.

cp ws-node-add /usr/bin
cp ws-node-remove /usr/bin
cp ws-project-add /usr/bin