#!/bin/php

<?php

#Include database file in user's home directory
$home = getenv("HOME");
if (!file_exists($home."/.ws-db.php")) {
  print(".ws-db.php does not exist.\nSee https://github.com/Wildlife-Systems/wildlife.systems-tools/wiki/.ws-db.php-does-not-exist\n\n");
  exit(1);
}
include($home."/.ws-db.php");


$mode = null;
if (!isset($argv[1]) || in_array($argv[1], array("help", "-h"))) {
  $mode = "help";
}

switch($mode) {
  case "help":
    print("Usage:\n");
    print("  ws-node-add node_id\n");
    print("\n");
    break;
  default:
    $sql = "INSERT INTO `nodes` VALUES('"
         . $db->real_escape_string($argv[1])
         . "', UUID());";
    if (!$result = $db->query($sql)) {
      print("Add node failed.\n\n");
      exit(2);
    } else {
      $sql = "SELECT `node_token` FROM `nodes` WHERE `node_id` = '"
           . $db->real_escape_string($argv[1])
           . "';";
      if ($result = $db->query($sql)) {
        $res_arr = $result->fetch_assoc();
        print("Node token: ");
        print($res_arr["node_token"]."\n\n");
      }
    }
}
